# Generated by Django 3.2.12 on 2023-04-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlisted', to='auctions.Listing'),
        ),
    ]
